<script>
var lang = {
    all: "{{trans('app.all')}}",
    processing: "{{trans('app.processing')}}",
    canceled: "{{trans('app.canceled')}}",
    failed: "{{trans('app.failed')}}",
    queue: "{{trans('app.queue')}}",
    sent: "{{trans('app.sent')}}",
    delivered: "{{trans('app.delivered')}}",
    undelivered: "{{trans('app.undelivered')}}",
    rejected: "{{trans('app.rejected')}}",
    name: "{{ trans('app.name') }}",
    email: "{{ trans('app.email') }}",
    active: "{{ trans('app.active') }}",
    status: "{{ trans('app.status') }}",
    created_at: "{{ trans('app.created_at') }}",
    generate_at: "{{ trans('app.generate_at') }}",
    created_by: "{{ trans('app.created_by') }}",
    file_type: "{{ trans('app.file_type') }}",
    end_date: "{{ trans('app.end_date') }}",
    start_date: "{{ trans('app.start_date') }}",
    company: "{{ trans('app.company') }}",
    action: "{{ str_plural(trans('app.action')) }}",
    delete: "{{ trans('app.delete') }}",
    edit: "{{ trans('app.edit') }}",
    daily: "{{trans('app.last_time',['value'=>24,'attribute'=>str_plural(trans('app.hour'))])}}",
    weekly: "{{trans('app.last_time',['value'=>7,'attribute'=>str_plural(trans('app.day'))])}}",
    monthly: "{{trans('app.last_time',['value'=>30,'attribute'=>str_plural(trans('app.day'))])}}",
    empty: "{{trans('app.empty_data')}}",
};
</script>